# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Get Version
      shell: pwsh
      run: |
        $xml = [xml](Get-Content '/home/runner/work/RankSSpawnHelper/RankSSpawnHelper/RankSSpawnHelper.csproj')  
        $version = $xml.Project.PropertyGroup.Version  
        echo "VERSION=$version" | Out-File -FilePath $ENV:GITHUB_ENV -Encoding utf8 -Append
    - name: Build
      run: dotnet publish -c Release
    - name: ZIP
      run: |
        cd /home/runner/work/RankSSpawnHelper/RankSSpawnHelper/RankSSpawnHelper/bin/Release/publish/
        zip -r release.zip .
        cd ..
        ls
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: /home/runner/work/RankSSpawnHelper/RankSSpawnHelper/RankSSpawnHelper/bin/Release/publish/release.zip
        tag_name: v${{ env.VERSION }} 
        make_latest: true
